### ISSUE TITLE
API & Guide generation doesn't work due to bad @bower alias in console app

### ISSUE THREAD

**Issue by ricpelo** [yiisoft/yii2-app-basic#152]
### What steps will reproduce the problem?

```
composer require "yiisoft/yii2-apidoc:~2.1.0"
```

Add `api` and `guide` to the `controllerMap` of `config/console.php`:
```
    'controllerMap' => [
        'api' => [
            'class' => 'yii\apidoc\commands\ApiController',
        ],
        'guide' => [
            'class' => 'yii\apidoc\commands\GuideController',
        ],
    ],
```

Run the API and guide generation:

```
./yii api . docs/api --pageTitle="API del proyecto" --guide=.. --guidePrefix= --exclude="docs,vendor,tests" --interactive=0
./yii guide guia docs --pageTitle="Guía del proyecto" --guidePrefix= --apiDocs=./api --interactive=0
```

### What's expected?

The API and guide documentation is generated OK.

### What do you get instead?

An error message which says the app is looking for a file into `vendor/bower` instead of `vendor/bower-asset`:

```
Rendering markdown files: 0% (0/2) ETA: n/a   Exception 'yii\base\InvalidParamException' with message 'The file or directory to be published does not exist: /home/ricardo/web/nuevo/vendor/bower/bootstrap/dist'

in /home/ricardo/web/nuevo/vendor/yiisoft/yii2/web/AssetManager.php:456

Stack trace:
#0 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/web/AssetBundle.php(185): yii\web\AssetManager->publish('/home/ricardo/w...', Array)
#1 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/web/AssetManager.php(268): yii\web\AssetBundle->publish(Object(yii\web\AssetManager))
#2 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/web/AssetManager.php(239): yii\web\AssetManager->loadBundle('yii\\bootstrap\\B...', Array, true)
#3 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/web/View.php(286): yii\web\AssetManager->getBundle('yii\\bootstrap\\B...')
#4 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/web/AssetBundle.php(125): yii\web\View->registerAssetBundle('yii\\bootstrap\\B...')
#5 /home/ricardo/web/nuevo/vendor/yiisoft/yii2-apidoc/templates/bootstrap/SideNavWidget.php(100): yii\web\AssetBundle::register(Object(yii\web\View))
#6 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/base/Widget.php(140): yii\apidoc\templates\bootstrap\SideNavWidget->run()
#7 /home/ricardo/web/nuevo/vendor/yiisoft/yii2-apidoc/templates/bootstrap/layouts/guide.php(43): yii\base\Widget::widget(Array)
#8 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/base/View.php(332): require('/home/ricardo/w...')
#9 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/home/ricardo/w...', Array)
#10 /home/ricardo/web/nuevo/vendor/yiisoft/yii2-apidoc/templates/html/GuideRenderer.php(103): yii\base\View->renderFile('/home/ricardo/w...', Array, Object(yii\apidoc\templates\bootstrap\GuideRenderer))
#11 /home/ricardo/web/nuevo/vendor/yiisoft/yii2-apidoc/templates/bootstrap/GuideRenderer.php(44): yii\apidoc\templates\html\GuideRenderer->render(Array, 'docs')
#12 /home/ricardo/web/nuevo/vendor/yiisoft/yii2-apidoc/commands/GuideController.php(96): yii\apidoc\templates\bootstrap\GuideRenderer->render(Array, 'docs')
#13 [internal function]: yii\apidoc\commands\GuideController->actionIndex(Array, 'docs')
#14 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#16 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/console/Controller.php(135): yii\base\Controller->runAction('', Array)
#17 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('', Array)
#18 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('guide', Array)
#19 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('guide', Array)
#20 /home/ricardo/web/nuevo/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#21 /home/ricardo/web/nuevo/yii(30): yii\base\Application->run()
#22 {main}
```

Rendering files: 0% (0/11) ETA: n/a   Exception 'yii\base\InvalidParamException' with message 'The file or directory to be published does not exist: /home/ricardo/web/nuevo/vendor/bower/bootstrap/dist'

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.13
| PHP version      | 7.1.11
| Operating system | Ubuntu 16.04.3 LTS

**Comment by samdark** [comment]
Seems to be solved.

**Comment by ansonhorse** [comment]
`yii2 v2.0.15.1` and `yii2-apidoc v2.1.0`
I still have this problem:
```
Rendering files: 0% (0/383) ETA: n/a   Error: The file or directory to be published does not exist: /path/to/vendor/yiisoft/yii2-apidoc/../../bower/bootstrap/dist
```
Could somebody tells me how to fix this? Thanks!
