### ISSUE TITLE
Using DataFactory prevents the successful destruction of test

### ISSUE THREAD

**Issue by g9m29** [yiisoft/yii2-app-basic#179]
### What steps will reproduce the problem?
codeception version

```
        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1",
        "codeception/specify": "~0.4.3"
```

1. Download base app
2. Configure DataFactory

in **functional.suits.yml**

```
- Yii2
      - DataFactory:
          factories: 'tests/_support/factories'
          depends: Yii2
```
3. Create custom database for the tests
4. Create definition for the model 

```
use app\models\Demo;
use League\FactoryMuffin\Faker\Facade as Faker;

$fm->define(Demo::class)->setDefinitions([
    'Title'   => Faker::word()
]);
```

5. Model is dummy model generated via gii

```
/**
 * This is the model class for table "demo".
 *
 * @property int $id
 * @property string $title
 */
class Demo extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'demo';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Title'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'Id' => 'ID',
            'Title' => 'Title',
        ];
    }

    /**
     * @inheritdoc
     */
    public function fields()
    {
        return [
            'id' => 'Id',
            'title' => 'Title'
        ];
    }
}
```

6. Call the definition in some random test

`$I->have(\app\models\Demo::class);`

### What's expected?

The value should be put into the database, the test should pass and then the database should be emptied

### What do you get instead?

```
An Error occurred while handling another error:
Error: Call to a member function has() on null in /var/www/html/df/vendor/yiisoft/yii2/web/ErrorHandler.php:91
Stack trace:
#0 /var/www/html/df/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(Error))
#1 [internal function]: yii\base\ErrorHandler->handleException(Object(Error))
#2 {main}
Previous exception:
Error: Call to a member function getDb() on null in /var/www/html/df/vendor/yiisoft/yii2/db/ActiveRecord.php:135
Stack trace:
#0 /var/www/html/df/vendor/yiisoft/yii2/db/ActiveRecord.php(382): yii\db\ActiveRecord::getDb()
#1 /var/www/html/df/vendor/yiisoft/yii2/db/ActiveRecord.php(408): yii\db\ActiveRecord::getTableSchema()
#2 /var/www/html/df/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1147): yii\db\ActiveRecord::primaryKey()
#3 /var/www/html/df/vendor/yiisoft/yii2/db/ActiveRecord.php(705): yii\db\BaseActiveRecord->getOldPrimaryKey(true)
#4 /var/www/html/df/vendor/yiisoft/yii2/db/ActiveRecord.php(669): yii\db\ActiveRecord->deleteInternal()
#5 /var/www/html/df/vendor/league/factory-muffin/src/Stores/ModelStore.php(80): yii\db\ActiveRecord->delete()
#6 /var/www/html/df/vendor/league/factory-muffin/src/Stores/AbstractStore.php(174): League\FactoryMuffin\Stores\ModelStore->delete(Object(app\models\Demo))
#7 /var/www/html/df/vendor/league/factory-muffin/src/FactoryMuffin.php(205): League\FactoryMuffin\Stores\AbstractStore->deleteSaved()
#8 /var/www/html/df/vendor/codeception/base/src/Codeception/Module/DataFactory.php(193): League\FactoryMuffin\FactoryMuffin->deleteSaved()
#9 /var/www/html/df/vendor/codeception/base/src/Codeception/Subscriber/Module.php(66): Codeception\Module\DataFactory->_after(Object(Codeception\Test\Cest))
#10 /var/www/html/df/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Codeception\Subscriber\Module->after(Object(Codeception\Event\TestEvent), 'test.after', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 /var/www/html/df/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'test.after', Object(Codeception\Event\TestEvent))
#12 /var/www/html/df/vendor/codeception/phpunit-wrapper/src/Listener.php(133): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('test.after', Object(Codeception\Event\TestEvent))
#13 /var/www/html/df/vendor/codeception/phpunit-wrapper/src/Listener.php(119): Codeception\PHPUnit\Listener->fire('test.after', Object(Codeception\Event\TestEvent))
#14 /var/www/html/df/vendor/phpunit/phpunit/src/Framework/TestResult.php(409): Codeception\PHPUnit\Listener->endTest(Object(Codeception\Test\Cest), 0.018405914306641)
#15 /var/www/html/df/vendor/codeception/base/src/Codeception/Test/Test.php(111): PHPUnit\Framework\TestResult->endTest(Object(Codeception\Test\Cest), 0.018405914306641)
#16 /var/www/html/df/vendor/phpunit/phpunit/src/Framework/TestSuite.php(760): Codeception\Test\Test->run(Object(PHPUnit\Framework\TestResult))
#17 /var/www/html/df/vendor/codeception/phpunit-wrapper/src/Runner.php(114): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#18 /var/www/html/df/vendor/codeception/base/src/Codeception/SuiteManager.php(157): Codeception\PHPUnit\Runner->doEnhancedRun(Object(Codeception\Suite), Object(PHPUnit\Framework\TestResult), Array)
#19 /var/www/html/df/vendor/codeception/base/src/Codeception/Codecept.php(189): Codeception\SuiteManager->run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit\Framework\TestResult), Array)
#20 /var/www/html/df/vendor/codeception/base/src/Codeception/Codecept.php(158): Codeception\Codecept->runSuite(Array, 'functional', NULL)
#21 /var/www/html/df/vendor/codeception/base/src/Codeception/Command/Run.php(466): Codeception\Codecept->run('functional')
#22 /var/www/html/df/vendor/codeception/base/src/Codeception/Command/Run.php(361): Codeception\Command\Run->runSuites(Array, Array)
#23 /var/www/html/df/vendor/symfony/console/Command/Command.php(252): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/df/vendor/symfony/console/Application.php(865): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/df/vendor/symfony/console/Application.php(241): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/df/vendor/symfony/console/Application.php(143): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/df/vendor/codeception/base/src/Codeception/Application.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/df/vendor/codeception/base/codecept(42): Codeception\Application->run()
#29 {main}
An Error occurred while handling another error:
Error: Call to a member function has() on null in /var/www/html/df/vendor/yiisoft/yii2/web/ErrorHandler.php:91
Stack trace:
#0 /var/www/html/df/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(Error))
#1 [internal function]: yii\base\ErrorHandler->handleException(Object(Error))
#2 {main}
Previous exception:
Error: Call to a member function getDb() on null in /var/www/html/df/vendor/yiisoft/yii2/db/ActiveRecord.php:135
Stack trace:
#0 /var/www/html/df/vendor/yiisoft/yii2/db/ActiveRecord.php(382): yii\db\ActiveRecord::getDb()
#1 /var/www/html/df/vendor/yiisoft/yii2/db/ActiveRecord.php(408): yii\db\ActiveRecord::getTableSchema()
#2 /var/www/html/df/vendor/yiisoft/yii2/db/BaseActiveRecord.php(1147): yii\db\ActiveRecord::primaryKey()
#3 /var/www/html/df/vendor/yiisoft/yii2/db/ActiveRecord.php(705): yii\db\BaseActiveRecord->getOldPrimaryKey(true)
#4 /var/www/html/df/vendor/yiisoft/yii2/db/ActiveRecord.php(669): yii\db\ActiveRecord->deleteInternal()
#5 /var/www/html/df/vendor/league/factory-muffin/src/Stores/ModelStore.php(80): yii\db\ActiveRecord->delete()
#6 /var/www/html/df/vendor/league/factory-muffin/src/Stores/AbstractStore.php(174): League\FactoryMuffin\Stores\ModelStore->delete(Object(app\models\Demo))
#7 /var/www/html/df/vendor/league/factory-muffin/src/FactoryMuffin.php(205): League\FactoryMuffin\Stores\AbstractStore->deleteSaved()
#8 /var/www/html/df/vendor/codeception/base/src/Codeception/Module/DataFactory.php(193): League\FactoryMuffin\FactoryMuffin->deleteSaved()
#9 /var/www/html/df/vendor/codeception/base/src/Codeception/Subscriber/Module.php(66): Codeception\Module\DataFactory->_after(Object(Codeception\Test\Cest))
#10 /var/www/html/df/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Codeception\Subscriber\Module->after(Object(Codeception\Event\TestEvent), 'test.after', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 /var/www/html/df/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'test.after', Object(Codeception\Event\TestEvent))
#12 /var/www/html/df/vendor/codeception/phpunit-wrapper/src/Listener.php(133): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('test.after', Object(Codeception\Event\TestEvent))
#13 /var/www/html/df/vendor/codeception/phpunit-wrapper/src/Listener.php(119): Codeception\PHPUnit\Listener->fire('test.after', Object(Codeception\Event\TestEvent))
#14 /var/www/html/df/vendor/phpunit/phpunit/src/Framework/TestResult.php(409): Codeception\PHPUnit\Listener->endTest(Object(Codeception\Test\Cest), 0.018405914306641)
#15 /var/www/html/df/vendor/codeception/base/src/Codeception/Test/Test.php(111): PHPUnit\Framework\TestResult->endTest(Object(Codeception\Test\Cest), 0.018405914306641)
#16 /var/www/html/df/vendor/phpunit/phpunit/src/Framework/TestSuite.php(760): Codeception\Test\Test->run(Object(PHPUnit\Framework\TestResult))
#17 /var/www/html/df/vendor/codeception/phpunit-wrapper/src/Runner.php(114): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#18 /var/www/html/df/vendor/codeception/base/src/Codeception/SuiteManager.php(157): Codeception\PHPUnit\Runner->doEnhancedRun(Object(Codeception\Suite), Object(PHPUnit\Framework\TestResult), Array)
#19 /var/www/html/df/vendor/codeception/base/src/Codeception/Codecept.php(189): Codeception\SuiteManager->run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit\Framework\TestResult), Array)
#20 /var/www/html/df/vendor/codeception/base/src/Codeception/Codecept.php(158): Codeception\Codecept->runSuite(Array, 'functional', NULL)
#21 /var/www/html/df/vendor/codeception/base/src/Codeception/Command/Run.php(466): Codeception\Codecept->run('functional')
#22 /var/www/html/df/vendor/codeception/base/src/Codeception/Command/Run.php(361): Codeception\Command\Run->runSuites(Array, Array)
#23 /var/www/html/df/vendor/symfony/console/Command/Command.php(252): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/df/vendor/symfony/console/Application.php(865): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/df/vendor/symfony/console/Application.php(241): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/df/vendor/symfony/console/Application.php(143): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/df/vendor/codeception/base/src/Codeception/Application.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/df/vendor/codeception/base/codecept(42): Codeception\Application->run()
#29 {main}
$_SERVER = [
    'HTTP_USER_AGENT' => 'Symfony BrowserKit',
    'SCRIPT_FILENAME' => 'index-test.php',
    'SCRIPT_NAME' => '/index-test.php',
    'SERVER_NAME' => 'localhost',
    'SERVER_PORT' => '80',
    'HTTPS' => false,
    'REQUEST_TIME' => 1522853166,
    'REQUEST_TIME_FLOAT' => 1522853166.976327,
    'HTTP_REFERER' => 'http://localhost/index-test.php?r=site%2Fcontact',
    'HTTP_HOST' => 'localhost',
    'REQUEST_URI' => '/index-test.php?r=site%2Fcontact',
    'REQUEST_METHOD' => 'POST',
]
PHP Fatal error:  Uncaught RuntimeException: Command Did Not Finish Properly in /var/www/html/df/vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php:101
Stack trace:
#0 [internal function]: Codeception\Subscriber\ErrorHandler->shutdownHandler()
#1 {main}
  thrown in /var/www/html/df/vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php on line 101

```

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2
| PHP version      | 7.1
| Operating system | Xubuntu

**Comment by cebe** [comment]
Seems `Yii::$app` is null in your case, make sure Yii module sets it up correctly.

**Comment by g9m29** [comment]
Yes that was the outcome of the issue. Thank you. To fix this I needed to remove the cleanup: false from codeception.yml and also put the transaction: true since the documentation says it defaults to true but the confing in the Yii2.php is set to null. Everything works as it should with those settings.
