### ISSUE TITLE
Can't run tests after creating yii2 project from from scratch

### ISSUE THREAD

**Issue by ilyachase** [yiisoft/yii2-app-basic#185]
### What steps will reproduce the problem?

1. composer create-project --prefer-dist yiisoft/yii2-app-basic
2. cd yii2-app-basic
3. ./vendor/bin/codecept run

### What's expected?
All tests has ran and passed.

### What do you get instead?
```
Codeception PHP Testing Framework v2.4.4
Powered by PHPUnit 7.1.5 by Sebastian Bergmann and contributors.

Warning: preg_match(): Compilation failed: missing terminating ] for character class at offset 16 in C:\web\OpenServer\domains\test.local\vendor\codeception\base\autoload.php on line 134

Warning: preg_match(): Compilation failed: missing terminating ] for character class at offset 16 in C:\web\OpenServer\domains\test.local\vendor\codeception\base\autoload.php on line 134

Functional Tests (10) ----------------------------------------------------------------------------------------------------------------------------------------

E ContactFormCest: Open contact page

Fatal error: Uncaught Error: Call to a member function stop() on null in C:\web\OpenServer\domains\test.local\vendor\codeception\base\src\Codeception\Module\Yii2.php:346
Stack trace:
#0 C:\web\OpenServer\domains\test.local\vendor\codeception\base\src\Codeception\Subscriber\Module.php(66): Codeception\Module\Yii2->_after(Object(Codeception\Test\Cest))
#1 C:\web\OpenServer\domains\test.local\vendor\symfony\event-dispatcher\EventDispatcher.php(212): Codeception\Subscriber\Module->after(Object(Codeception\Event\TestEvent), 'test.after', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 C:\web\OpenServer\domains\test.local\vendor\symfony\event-dispatcher\EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'test.after', Object(Codeception\Event\TestEvent))
#3 C:\web\OpenServer\domains\test.local\vendor\codeception\phpunit-wrapper\src\Listener.php(133): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('test.after', Object(Codeception\Event\TestEvent))
#4 C:\web\Ope in C:\web\OpenServer\domains\test.local\vendor\codeception\base\src\Codeception\Module\Yii2.php on line 346

FATAL ERROR. TESTS NOT FINISHED.
Uncaught Error: Call to a member function stop() on null in C:\web\OpenServer\domains\test.local\vendor\codeception\base\src\Codeception\Module\Yii2.php:346
Stack trace:
#0 C:\web\OpenServer\domains\test.local\vendor\codeception\base\src\Codeception\Subscriber\Module.php(66): Codeception\Module\Yii2->_after(Object(Codeception\Test\Cest))
#1 C:\web\OpenServer\domains\test.local\vendor\symfony\event-dispatcher\EventDispatcher.php(212): Codeception\Subscriber\Module->after(Object(Codeception\Event\TestEvent), 'test.after', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 C:\web\OpenServer\domains\test.local\vendor\symfony\event-dispatcher\EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'test.after', Object(Codeception\Event\TestEvent))
#3 C:\web\OpenServer\domains\test.local\vendor\codeception\phpunit-wrapper\src\Listener.php(133): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('test.after', Object(Codeception\Event\TestEvent))
#4 C:\web\Ope
in C:\web\OpenServer\domains\test.local\vendor\codeception\base\src\Codeception\Module\Yii2.php:346
```

### Additional info
Wanted to implement some Unit tests in my project. But for some reason they're not working even in clean yii2 basic app as well as in my project (same error). And I couldn't find the reason fast. I think that somehow related with `_before` and `_after` methods. It seems that for module `Codeception\Module\Yii2` it runs `_after` but didn't ran `_before`.

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.14
| PHP version      | PHP 7.1.0
| Operating system | Windows 10

**Comment by ilyachase** [comment]
Also there are some weird warnings related to regular expression in codeception itself.

**Comment by inder-miracle** [comment]
New setup of yii2-app-basic with fresh composer install works fine.
but i am trying to run codecept on project where i was working from 1 year, 
it was working fine few months back, but i don't know due to updates in composer codecept is failing
with following exception.

```
$ ./vendor/bin/codecept run
Codeception PHP Testing Framework v2.4.4
Powered by PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Warning: preg_match(): Compilation failed: missing terminating ] for character c                  lass at offset 16 in C:\wamp64\www\project\vendor\codeception\codecepti                  on\autoload.php on line 134

Functional Tests (10) ----------------------------------------------------------
E ContactFormCest: Open contact page

Fatal error: Call to a member function stop() on null in C:\wamp64\www\vms-git-s                  ecurity\vendor\codeception\codeception\src\Codeception\Module\Yii2.php on line 3                  46

FATAL ERROR. TESTS NOT FINISHED.
Call to a member function stop() on null
in C:\wamp64\www\project\vendor\codeception\codeception\src\Codeception                  \Module\Yii2.php:346

```

**Comment by ilyachase** [comment]
> New setup of yii2-app-basic with fresh composer install works fine.
Not true for me. It fails persistently, with same errors that you mentioned.

May be it broke with PHP version updates?

**Comment by inder-miracle** [comment]
may be, 
my php yii 2 version 2.0.5 with codecept 2.4.4 have issue
but the latest yii2 version  2.0.14 works fine with codecept. 2.4.4

**Comment by inder-miracle** [comment]
please share your composer.json file content

**Comment by ilyachase** [comment]
What do you mean mine?
I'm creating new project from scratch.

`https://github.com/yiisoft/yii2-app-basic/blob/master/composer.json`

**Comment by inder-miracle** [comment]
No clue,  it should work with latest composer.json

**Comment by ilyachase** [comment]
Tried on another machine with php 7.0.
Still getting errors, other ones this time.

> [Error] Class 'PHPUnit_Framework_Assert' not found

Attached screencast.
![tests](https://user-images.githubusercontent.com/1961077/43386360-d55542e0-93fc-11e8-88ee-f125bb42f6b7.gif)

**Comment by tebazil** [comment]
I have a same error. Tried to update codeception to 2.4  - that didn't help.

Here are my thoughts:
> codeception\base\src\Codeception\Module\Yii2.php:346

Is _after method:

```php
public function _after(TestInterface $test)
    {
        $_SESSION = [];
        $_FILES = [];
        $_GET = [];
        $_POST = [];
        $_COOKIE = [];
        $_REQUEST = [];

        $this->rollbackTransactions();

        $this->connectionWatcher->stop();
        $this->connectionWatcher->closeAll();
```

`connectionWatcher' is a private member that defaults to null

... and it is initialized in `_before` method

```php
public function _before(TestInterface $test)
    {
        $this->recreateClient();
        $this->client->startApp();

        $this->connectionWatcher = new Yii2Connector\ConnectionWatcher();
        $this->connectionWatcher->start();
```
It seems that this _before method isn't run at all...
If so, the question is 'why'?

**Comment by tebazil** [comment]
Hmm, it seems I found something.. there is this PR at codeception that seems to fix the issue... https://github.com/Codeception/Codeception/pull/5136
When I reviewed it's code, and tried to apply some fixes, this seemed to work:

`codeception\base\src\Codeception\Module\Yii2.php`

```php
if($this->connectionWatcher) { //change
            $this->connectionWatcher->stop();
            $this->connectionWatcher->closeAll();
            unset($this->connectionWatcher);
        } //change

        if ($this->config['cleanup']) {
            foreach ($this->loadedFixtures as $fixture) {
                $fixture->unloadFixtures();
            }
            $this->loadedFixtures = [];
        }

        if ($this->client !== null && $this->client->getApplication()->has('session', true)) {
            $this->client->getApplication()->session->close();
        }

        if($this->client) { //change
            $this->client->resetApplication();
        } //change
```
My changes are marked with `//change`

**Comment by samdark** [comment]
Closing since that PR is now merged.
