### ISSUE TITLE
UrlManager::buildRules() called with a boolean instead of array when unit testing

### ISSUE THREAD

**Issue by cyril-amar** [yiisoft/yii2-app-basic#306]
### What steps will reproduce the problem?
1. Create a custom module, implementing `yii\base\BootstrapInterface` and extending an abstract class itself extending `yii\base\Module` (only adding parameters/methods, not surcharging any)
2. Add pretty URLs from the `Module::bootstrap()` method
```
$app->getUrlManager()->addRules([
            [
                'verb'    => 'GET',
                'pattern' => '/org/config/incident/severity',
                'route'   => '/incident/severity-level/index',
            ],
            [
                'verb'    => 'GET,POST',
                'pattern' => '/org/config/incident/severity/new',
                'route'   => '/incident/severity-level/create',
            ],
            [
                'verb'    => 'GET,POST',
                'pattern' => '/org/config/incident/severity/<id:[0-9]+>/<action:(update|delete)>',
                'route'   => '/incident/severity-level/<action>',
            ],
        ], false);
```
3. Add the module in `Yii::$app->bootstrap` in the config file used by testing.
4. Run unit tests
`$> vendor/bin/codecept run unit`

### What's expected?
Tests are run.

### What do you get instead?
First test in run OK, all others are met with:
```                                                                              
  [yii\base\ErrorException] foreach() argument must be of type array|object, bool given  
                                                                                         
#1  /home/clients/<my_customer_path>/vendor/yiisoft/yii2/web/UrlManager.php:241
#2  /home/clients/<my_customer_path>/vendor/yiisoft/yii2/web/UrlManager.php:193
#3  /home/clients/<my_customer_path>/vendor/yiisoft/yii2/base/BaseObject.php:109
#4  yii\base\BaseObject->__construct
#5  /home/clients/<my_customer_path>/vendor/yiisoft/yii2/di/Container.php:419
#6  /home/clients/<my_customer_path>/vendor/yiisoft/yii2/di/Container.php:170
#7  /home/clients/<my_customer_path>/vendor/yiisoft/yii2/BaseYii.php:365
#8  /home/clients/<my_customer_path>/vendor/yiisoft/yii2/di/ServiceLocator.php:137
#9  /home/clients/<my_customer_path>/vendor/yiisoft/yii2/base/Module.php:766
#10 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/base/Application.php:569
```

### Additional info

Running the app while not in unit testing works fine. The custom module is only bootstrapped, not tested (yet!).

I determined that `UrlManager::buildRules()` in `yii2/web/UrlManager.php:228` is called with `true` instead of an array (viewed by dumping the value). Declaring `UrlManager::$rules` as an array on `UrlManager.php:105` provokes indeed an error:

```
TypeError: Cannot assign bool to property yii\web\UrlManager::$rules of type array in /home/clients/<my_customer_path>/vendor/yiisoft/yii2/BaseYii.php:558
Stack trace:
#0 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(yii\web\UrlManager), Array)
#1 [internal function]: yii\base\BaseObject->__construct(Array)
#2 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#3 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('yii\\web\\UrlMana...', Array, Array)
#4 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('yii\\web\\UrlMana...', Array, Array)
#5 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#6 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/base/Module.php(766): yii\di\ServiceLocator->get('urlManager', true)
#7 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/base/Application.php(569): yii\base\Module->get('urlManager')
#8 /home/clients/<my_customer_path>/modules/incident/Module.php(69): yii\base\Application->getUrlManager()
#9 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/base/Application.php(325): app\modules\incident\Module->bootstrap(Object(yii\web\Application))
#10 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/web/Application.php(69): yii\base\Application->bootstrap()
#11 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/base/Application.php(271): yii\web\Application->bootstrap()
#12 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/base/BaseObject.php(109): yii\base\Application->init()
#13 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#14 [internal function]: yii\base\Application->__construct(Array)
#15 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#16 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('yii\\web\\Applica...', Array, Array)
#17 /home/clients/<my_customer_path>/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('yii\\web\\Applica...', Array, Array)
#18 /home/clients/<my_customer_path>/vendor/codeception/module-yii2/src/Codeception/Lib/Connector/Yii2.php(299): yii\BaseYii::createObject(Array)
#19 /home/clients/<my_customer_path>/vendor/codeception/module-yii2/src/Codeception/Module/Yii2.php(329): Codeception\Lib\Connector\Yii2->startApp(Object(Codeception\Lib\Connector\Yii2\Logger))
#20 /home/clients/<my_customer_path>/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php(70): Codeception\Module\Yii2->_before(Object(Codeception\Test\TestCaseWrapper))
#21 /home/clients/<my_customer_path>/vendor/symfony/event-dispatcher/EventDispatcher.php(220): Codeception\Subscriber\Module->before(Object(Codeception\Event\TestEvent), 'test.before', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#22 /home/clients/<my_customer_path>/vendor/symfony/event-dispatcher/EventDispatcher.php(56): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'test.before', Object(Codeception\Event\TestEvent))
#23 /home/clients/<my_customer_path>/vendor/codeception/codeception/src/Codeception/Test/Test.php(296): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Codeception\Event\TestEvent), 'test.before')
#24 /home/clients/<my_customer_path>/vendor/codeception/codeception/src/Codeception/Test/Test.php(149): Codeception\Test\Test->fire('test.before', Object(Codeception\Event\TestEvent))
#25 /home/clients/<my_customer_path>/vendor/codeception/codeception/src/Codeception/Suite.php(130): Codeception\Test\Test->realRun(Object(Codeception\ResultAggregator))
#26 /home/clients/<my_customer_path>/vendor/codeception/codeception/src/Codeception/SuiteManager.php(148): Codeception\Suite->run(Object(Codeception\ResultAggregator))
#27 /home/clients/<my_customer_path>/vendor/codeception/codeception/src/Codeception/Codecept.php(260): Codeception\SuiteManager->run(Object(Codeception\ResultAggregator))
#28 /home/clients/<my_customer_path>/vendor/codeception/codeception/src/Codeception/Codecept.php(216): Codeception\Codecept->runSuite(Array, 'unit', NULL)
#29 /home/clients/<my_customer_path>/vendor/codeception/codeception/src/Codeception/Command/Run.php(646): Codeception\Codecept->run('unit')
#30 /home/clients/<my_customer_path>/vendor/codeception/codeception/src/Codeception/Command/Run.php(467): Codeception\Command\Run->runSuites(Array, Array)
#31 /home/clients/<my_customer_path>/vendor/symfony/console/Command/Command.php(326): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /home/clients/<my_customer_path>/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /home/clients/<my_customer_path>/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /home/clients/<my_customer_path>/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /home/clients/<my_customer_path>/vendor/codeception/codeception/src/Codeception/Application.php(112): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /home/clients/<my_customer_path>/vendor/codeception/codeception/app.php(45): Codeception\Application->run()
#37 /home/clients/<my_customer_path>/vendor/codeception/codeception/app.php(46): {closure}()
#38 /home/clients/<my_customer_path>/vendor/codeception/codeception/codecept(7): require('/home/clients/5...')
#39 /home/clients/<my_customer_path>/vendor/bin/codecept(120): include('/home/clients/5...')
#40 {main}
```

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.48.1
| PHP version      | 8.2
| Operating system | Linux, specifics unavailable

**Comment by particleflux** [comment]
Cannot reproduce in basic app.

Created a module using:

```shell
./yii gii/module --moduleClass 'app\modules\Test\Module' --moduleID test
```

Edited it to implement `BootstrapInterface` and add custom url rules on bootstrap:

```php
<?php

namespace app\modules\Test;

use yii\base\BootstrapInterface;

/**
 * test module definition class
 */
class Module extends \yii\base\Module implements BootstrapInterface
{
    /**
     * {@inheritdoc}
     */
    public $controllerNamespace = 'app\modules\Test\controllers';

    /**
     * {@inheritdoc}
     */
    public function init()
    {
        parent::init();

        // custom initialization code goes here
    }

    public function bootstrap($app)
    {
        $app->getUrlManager()->addRules([
            [
                'verb'    => 'GET',
                'pattern' => '/org/config/incident/severity',
                'route'   => '/incident/severity-level/index',
            ],
            [
                'verb'    => 'GET,POST',
                'pattern' => '/org/config/incident/severity/new',
                'route'   => '/incident/severity-level/create',
            ],
            [
                'verb'    => 'GET,POST',
                'pattern' => '/org/config/incident/severity/<id:[0-9]+>/<action:(update|delete)>',
                'route'   => '/incident/severity-level/<action>',
            ],
        ], false);
    }
}
```

Added to `config/test.php`:

```
    'bootstrap' => [
        'class' => app\modules\Test\Module::class,
    ],
    'modules'             => [
        'admin'     => [
            'class' => app\modules\Test\Module::class
        ],
    ]
```

Tests run fine. (both unit tests and full test suites, including functional)

Any more info you can give? Or maybe a minimal reproduction project in a zip?
